spring.datasource.url=jdbc:mysql://localhost:3306/circo_adrianintriago?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.data.mongodb.uri=mongodb://localhost:27017/circoDB
spring.data.mongodb.database=circo_adrian

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


objectdb.url=ficheros/incidencias.odb
objectdb.username=admin
objectdb.password=admin

existdb.url=xmldb:exist://localhost:8080/exist/xmlrpc
existdb.user=admin
existdb.password=admin
existdb.collection=/db/informes